Add Chameleon-supported appliances
ChameleonCloud/heat-templates pull request #2
Opened 2018-08-03 14:56 UTC by diurnalist

Leaving this here, maybe it makes sense to have these in this repo, maybe not.

2018-08-03 16:28 UTC, priteau requested changes

2018-08-03 16:28 UTC, priteau commented on hello-world/hello-world.yaml
> +description: NFS server and client deployed with Heat on Chameleon
Maybe we should update the description and remove the NFS bits from hello-world appliance, since we have a separate proper NFS appliance.

2018-08-06 14:44 UTC, priteau commented
@diurnalist I think we had a misunderstanding about the "Hello World" appliance: I was suggesting to simplify it by removing the parts that are specific to NFS (maybe just launch some instances using an ResourceGroup), not removing the template entirely.

2018-08-06 14:46 UTC, diurnalist commented
@priteau ah yes, I see what you mean now. I'll bring it back in a simpler format.

2018-08-09 19:00 UTC, diurnalist commented
@priteau I have updated the Hello World appliance to use a new (very contrived!) example for demonstration purposes.

2018-08-10 16:59 UTC, priteau approved these changes
Looks good!

2018-08-15 16:05 UTC, zhenz commented
@diurnalist Do we have an auto-sync mechanism between this repo and Appliance Catalog? or do we have to manually do the sync?

2018-08-15 16:10 UTC, diurnalist commented
@zhenz there is no automatic sync as of yet.

2018-08-15 16:10 UTC, merged